name: Main CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.changes.outputs.client }}
      server: ${{ steps.changes.outputs.server }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          client:
            - 'client/**'
          server:
            - 'server/**'

  summary:
    runs-on: ubuntu-latest
    needs: [check-changes]
    steps:
    - name: Build Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Client changes: ${{ needs.check-changes.outputs.client }}" >> $GITHUB_STEP_SUMMARY
        echo "- Server changes: ${{ needs.check-changes.outputs.server }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Individual workflows will run based on changed files." >> $GITHUB_STEP_SUMMARY