# Server CI for Egg.js backend

name: Server CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        cd server
        yarn install

    - name: Run CI (lint + coverage)
      run: |
        cd server
        npm run ci

    - name: Build application
      run: |
        cd server
        npm run build
