# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Install Dependencies
      run: |
        cd server
        npm ci

    - name: Lint Code
      run: |
        cd server
        npm run lint

    - name: Run Tests
      run: |
        cd server
        npm run test-local

    - name: Build Application
      run: |
        cd server
        npm run build

    - name: Code Coverage
      if: matrix.node-version == '18' && matrix.os == 'ubuntu-latest'
      run: |
        cd server
        npm run cov

    - name: Upload Coverage to Codecov
      if: matrix.node-version == '18' && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
      with:
        file: ./server/coverage/lcov.info
        flags: server
        name: server-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
